//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatesOrtho
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BatesOrthoEntities : DbContext
    {
        public BatesOrthoEntities()
            : base("name=BatesOrthoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DoctorReferral> DoctorReferrals { get; set; }
        public virtual DbSet<FriendReferral> FriendReferrals { get; set; }
        public virtual DbSet<SponsershipRequestAdType> SponsershipRequestAdTypes { get; set; }
        public virtual DbSet<SponsorshipRequest> SponsorshipRequests { get; set; }
        public virtual DbSet<PreferredAppointmentDay> PreferredAppointmentDays { get; set; }
        public virtual DbSet<AppointmentRequest> AppointmentRequests { get; set; }
    }
}
