//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatesOrtho
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorReferral
    {
        public int DoctorReferralID { get; set; }
        public string DoctorFirstName { get; set; }
        public string DoctorLastName { get; set; }
        public string PracticeName { get; set; }
        public string DoctorEmail { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public string PatientPhoneNumber { get; set; }
        public string PatientEmailAddress { get; set; }
        public string RadiographsSent { get; set; }
        public string Comments { get; set; }
    }
}
