//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatesOrtho
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferredAppointmentDay
    {
        public int PreferredAppointmentDayID { get; set; }
        public string AppointmentRequestDay { get; set; }
        public Nullable<int> AppointmentRequestID { get; set; }
    }
}
