//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatesOrtho
{
    using System;
    using System.Collections.Generic;
    
    public partial class SponsorshipRequest
    {
        public SponsorshipRequest()
        {
            this.SponsershipRequestAdTypes = new HashSet<SponsershipRequestAdType>();
        }
    
        public int SponsorshipRequestID { get; set; }
        public System.DateTime Date { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string PatientTreatmentStatus { get; set; }
        public string Organization { get; set; }
        public string CheckPayableTo { get; set; }
        public string SendCheckToAddress { get; set; }
        public string SendCheckToAddress2 { get; set; }
        public string SendCheckToCity { get; set; }
        public string SendCheckToState { get; set; }
        public string SendCheckToZip { get; set; }
        public string Comments { get; set; }
    
        public virtual ICollection<SponsershipRequestAdType> SponsershipRequestAdTypes { get; set; }
    }
}
