//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatesOrtho
{
    using System;
    using System.Collections.Generic;
    
    public partial class SponsershipRequestAdType
    {
        public int SponsorshipRequestAdTypeID { get; set; }
        public Nullable<int> SponsorshipRequestID { get; set; }
        public string AdType { get; set; }
        public string AdTypeDescription { get; set; }
        public string AdSize { get; set; }
        public Nullable<decimal> AdCost { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual SponsorshipRequest SponsorshipRequest { get; set; }
    }
}
